version: '3'
services:
  be: # Ruby on Railsが起動するコンテナ
    container_name: be-app
    build: ./be
    command: "bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
    volumes:
      - ./be:/be # アプリケーションファイルの同期
    depends_on:
      - rdb
    stdin_open: true
    tty: true

  rdb: # MySQLが起動するコンテナ
    container_name: rdb
    # platform: 'linux/amd64' # intel Macの場合
    platform: linux/x86_64 # M1 Mac
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password # 認証方式(8系以前)
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

volumes:
  mysql_data:
    driver: local
