default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  username: <%= ENV.fetch("DATABASE_USER", 'root') %>
  password: <%= ENV.fetch("DATABASE_PASS", 'root') %>
  host: <%= ENV.fetch("DATABASE_HOST", 'rdb') %>
  port: <%= ENV.fetch("DATABASE_PORT"){ 3306 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: be_development

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", 'be_test') %>
  host: rdb

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", 'be_production') %>
  username: <%= ENV.fetch("DATABASE_USERNAME", 'root') %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", 'root') %>
  host: <%= ENV.fetch("DATABASE_HOST", 'rdb') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # sslca: "/etc/ssl/cert.pem"
